version: "3.9"

services:
    maven:
        build: maven_host
        image: maven_boxfuse:latest
        volumes:
            - webapps:/tmp/webapps
    tomcat:
        image: tomcat:9.0.46-jdk16-openjdk-slim-buster
        volumes:
            - webapps:/usr/local/tomcat/webapps
        ports:
            - "8080:8080"
volumes:
    webapps: